export { BlendingMode };
export { BlendingEquation };
export { BufferDataUsage };
export { BufferMask };
export { BufferMaskBit };
export { BufferBindingPoint };
export { BufferIndexType };
export { BufferInterpolation };
export { BufferTarget };
export { Capabilities };
export { CullFaceMode };
export { DrawMode };
export { DataType };
export { Error };
export { FramebufferAttachment };
export { FramebufferAttachmentParameter };
export { FramebufferTarget };
export { FramebufferTextureTarget };
export { FrontFace };
export { HintTarget };
export { HintMode };
export { Parameter };
export { PixelFormat };
export { PixelStorageMode };
export { PixelType };
export { RenderbufferTarget };
export { Shader };
export { ShaderType };
export { ShaderPrecision };
export { StencilAction };
export { TestFunction };
export { TextureUnits };
export { TextureParameter };
export { TextureTarget };
export { TextureMagFilter };
export { TextureMinFilter };
export { TextureWrapMode };
export { UniformQuery };
export { UniformType };
export { VertexAttribute };
declare enum BlendingMode {
    ZERO,
    ONE,
    SRC_COLOR,
    ONE_MINUS_SRC_COLOR,
    DST_COLOR,
    ONE_MINUS_DST_COLOR,
    SRC_ALPHA,
    ONE_MINUS_SRC_ALPHA,
    ONE_MINUS_DST_ALPHA,
    CONSTANT_COLOR,
    ONE_MINUS_CONSTANT_COLOR,
    CONSTANT_ALPHA,
    ONE_MINUS_CONSTANT_ALPHA,
    SRC_ALPHA_SATURATE
}
declare enum BlendingEquation {
    FUNC_ADD,
    FUNC_SUBTRACT,
    FUNC_REVERSE_SUBTRACT,
    MIN,
    MAX
}
declare enum BufferMaskBit {
    DEPTH_BUFFER_BIT,
    STENCIL_BUFFER_BIT,
    COLOR_BUFFER_BIT
}
declare enum BufferMask {
    DEPTH,
    STENCIL,
    COLOR,
    DEPTH_STENCIL
}
declare enum BufferDataUsage {
    STATIC_DRAW,
    DYNAMIC_DRAW,
    STREAM_DRAW,
    STATIC_READ,
    DYNAMIC_READ,
    STREAM_READ,
    STATIC_COPY,
    DYNAMIC_COPY,
    STREAM_COPY
}
declare enum BufferBindingPoint {
    ARRAY_BUFFER,
    ELEMENT_ARRAY_BUFFER,
    COPY_READ_BUFFER,
    COPY_WRITE_BUFFER,
    TRANSFORM_FEEDBACK_BUFFER,
    UNIFORM_BUFFER,
    PIXEL_PACK_BUFFER,
    PIXEL_UNPACK_BUFFER
}
declare enum BufferIndexType {
    UNSIGNED_BYTE,
    UNSIGNED_SHORT,
    UNSIGNED_INT
}
declare enum BufferInterpolation {
    LINEAR,
    NEAREST
}
declare enum BufferTarget {
    ARRAY_BUFFER,
    ELEMENT_ARRAY_BUFFER,
    COPY_READ_BUFFER,
    COPY_WRITE_BUFFER,
    TRANSFORM_FEEDBACK_BUFFER,
    UNIFORM_BUFFER,
    PIXEL_PACK_BUFFER,
    PIXEL_UNPACK_BUFFER
}
declare enum Capabilities {
    BLEND,
    CULL_FACE,
    DEPTH_TEST,
    DITHER,
    POLYGON_OFFSET_FILL,
    SAMPLE_ALPHA_TO_COVERAGE,
    SAMPLE_COVERAGE,
    SCISSOR_TEST,
    STENCIL_TEST,
    RASTERIZER_DISCARD
}
declare enum CullFaceMode {
    FRONT,
    BACK,
    FRONT_AND_BACK
}
declare enum DrawMode {
    POINTS,
    LINE_STRIP,
    LINE_LOOP,
    LINES,
    TRIANGLE_STRIP,
    TRIANGLE_FAN,
    TRIANGLES
}
declare enum DataType {
    BYTE,
    SHORT,
    UNSIGNED_BYTE,
    UNSIGNED_SHORT,
    FLOAT,
    HALF_FLOAT
}
declare enum Error {
    NO_ERROR,
    INVALID_ENUM,
    INVALID_OPERATION,
    OUT_OF_MEMORY,
    CONTEXT_LOST_WEBGL
}
declare enum FramebufferAttachment {
    COLOR_ATTACHMENT0,
    COLOR_ATTACHMENT1,
    COLOR_ATTACHMENT2,
    COLOR_ATTACHMENT3,
    COLOR_ATTACHMENT4,
    COLOR_ATTACHMENT5,
    COLOR_ATTACHMENT6,
    COLOR_ATTACHMENT7,
    COLOR_ATTACHMENT8,
    COLOR_ATTACHMENT9,
    COLOR_ATTACHMENT10,
    COLOR_ATTACHMENT11,
    COLOR_ATTACHMENT12,
    COLOR_ATTACHMENT13,
    COLOR_ATTACHMENT14,
    COLOR_ATTACHMENT15,
    DEPTH_ATTACHMENT,
    STENCIL_ATTACHMENT,
    DEPTH_STENCIL_ATTACHMENT
}
declare enum FramebufferAttachmentParameter {
    FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE,
    FRAMEBUFFER_ATTACHMENT_OBJECT_NAME,
    FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL,
    FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE,
    FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE,
    FRAMEBUFFER_ATTACHMENT_BLUE_SIZE,
    FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING,
    FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE,
    FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE,
    FRAMEBUFFER_ATTACHMENT_GREEN_SIZE,
    FRAMEBUFFER_ATTACHMENT_RED_SIZE,
    FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE,
    FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER
}
declare enum FramebufferTarget {
    FRAMEBUFFER,
    DRAW_FRAMEBUFFER,
    READ_FRAMEBUFFER
}
declare enum FramebufferTextureTarget {
    TEXTURE_2D,
    TEXTURE_CUBE_MAP_POSITIVE_X,
    TEXTURE_CUBE_MAP_NEGATIVE_X,
    TEXTURE_CUBE_MAP_POSITIVE_Y,
    TEXTURE_CUBE_MAP_NEGATIVE_Y,
    TEXTURE_CUBE_MAP_POSITIVE_Z,
    TEXTURE_CUBE_MAP_NEGATIVE_Z
}
declare enum FrontFace {
    CW,
    CCW
}
declare enum HintTarget {
    GENERATE_MIPMAP_HINT,
    FRAGMENT_SHADER_DERIVATIVE_HINT
}
declare enum HintMode {
    FASTEST,
    NICEST,
    DONT_CARE
}
declare enum Parameter {
    ACTIVE_TEXTURE,
    ALIASED_LINE_WIDTH_RANGE,
    ALIASED_POINT_SIZE_RANGE,
    ALPHA_BITS,
    ARRAY_BUFFER_BINDING,
    BLEND,
    BLEND_COLOR,
    BLEND_DST_ALPHA,
    BLEND_DST_RGB,
    BLEND_EQUATION,
    BLEND_EQUATION_ALPHA,
    BLEND_EQUATION_RGB,
    BLEND_SRC_ALPHA,
    BLEND_SRC_RGB,
    BLUE_BITS,
    COLOR_CLEAR_VALUE,
    COLOR_WRITEMASK,
    COMPRESSED_TEXTURE_FORMATS,
    CULL_FACE,
    CULL_FACE_MODE,
    CURRENT_PROGRAM,
    DEPTH_BITS,
    DEPTH_CLEAR_VALUE,
    DEPTH_FUNC,
    DEPTH_RANGE,
    DEPTH_TEST,
    DEPTH_WRITEMASK,
    DITHER,
    ELEMENT_ARRAY_BUFFER_BINDING,
    FRAMEBUFFER_BINDING,
    FRONT_FACE,
    GENERATE_MIPMAP_HINT,
    GREEN_BITS,
    IMPLEMENTATION_COLOR_READ_FORMAT,
    IMPLEMENTATION_COLOR_READ_TYPE,
    LINE_WIDTH,
    MAX_COMBINED_TEXTURE_IMAGE_UNITS,
    MAX_CUBE_MAP_TEXTURE_SIZE,
    MAX_FRAGMENT_UNIFORM_VECTORS,
    MAX_RENDERBUFFER_SIZE,
    MAX_TEXTURE_IMAGE_UNITS,
    MAX_TEXTURE_SIZE,
    MAX_VARYING_VECTORS,
    MAX_VERTEX_ATTRIBS,
    MAX_VERTEX_UNIFORM_VECTORS,
    MAX_VIEWPORT_DIMS,
    PACK_ALIGNMENT,
    POLYGON_OFFSET_FACTOR,
    POLYGON_OFFSET_FILL,
    POLYGON_OFFSET_UNITS,
    RED_BITS,
    RENDERBUFFER_BINDING,
    RENDERER,
    SAMPLE_BUFFERS,
    SAMPLE_COVERAGE_INVERT,
    SAMPLE_COVERAGE_VALUE,
    SAMPLES,
    SCISSOR_BOX,
    SCISSOR_TEST,
    SHADING_LANGUAGE_VERSION,
    STENCIL_BACK_FAIL,
    STENCIL_BACK_FUNC,
    STENCIL_BACK_PASS_DEPTH_FAIL,
    STENCIL_BACK_PASS_DEPTH_PASS,
    STENCIL_BACK_REF,
    STENCIL_BACK_VALUE_MASK,
    STENCIL_BACK_WRITEMASK,
    STENCIL_BITS,
    STENCIL_CLEAR_VALUE,
    STENCIL_FAIL,
    STENCIL_FUNC,
    STENCIL_PASS_DEPTH_FAIL,
    STENCIL_PASS_DEPTH_PASS,
    STENCIL_REF,
    STENCIL_TEST,
    STENCIL_VALUE_MASK,
    STENCIL_WRITEMASK,
    SUBPIXEL_BITS,
    TEXTURE_BINDING_2D,
    TEXTURE_BINDING_CUBE_MAP,
    UNPACK_ALIGNMENT,
    UNPACK_COLORSPACE_CONVERSION_WEBGL,
    UNPACK_FLIP_Y_WEBGL,
    UNPACK_PREMULTIPLY_ALPHA_WEBGL,
    VENDOR,
    VERSION,
    VIEWPORT,
    COPY_READ_BUFFER_BINDING,
    COPY_WRITE_BUFFER_BINDING,
    DRAW_FRAMEBUFFER_BINDING,
    FRAGMENT_SHADER_DERIVATIVE_HINT,
    MAX_3D_TEXTURE_SIZE,
    MAX_ARRAY_TEXTURE_LAYERS,
    MAX_CLIENT_WAIT_TIMEOUT_WEBGL,
    MAX_COLOR_ATTACHMENTS,
    MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS,
    MAX_COMBINED_UNIFORM_BLOCKS,
    MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS,
    MAX_DRAW_BUFFERS,
    MAX_ELEMENT_INDEX,
    MAX_ELEMENTS_INDICES,
    MAX_ELEMENTS_VERTICES,
    MAX_FRAGMENT_INPUT_COMPONENTS,
    MAX_FRAGMENT_UNIFORM_BLOCKS,
    MAX_FRAGMENT_UNIFORM_COMPONENTS,
    MAX_PROGRAM_TEXEL_OFFSET,
    MAX_SAMPLES,
    MAX_SERVER_WAIT_TIMEOUT,
    MAX_TEXTURE_LOD_BIAS,
    MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS,
    MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS,
    MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS,
    MAX_UNIFORM_BLOCK_SIZE,
    MAX_UNIFORM_BUFFER_BINDINGS,
    MAX_VARYING_COMPONENTS,
    MAX_VERTEX_OUTPUT_COMPONENTS,
    MAX_VERTEX_UNIFORM_BLOCKS,
    MAX_VERTEX_UNIFORM_COMPONENTS,
    MIN_PROGRAM_TEXEL_OFFSET,
    PACK_ROW_LENGTH,
    PACK_SKIP_PIXELS,
    PACK_SKIP_ROWS,
    PIXEL_PACK_BUFFER_BINDING,
    PIXEL_UNPACK_BUFFER_BINDING,
    RASTERIZER_DISCARD,
    READ_BUFFER,
    READ_FRAMEBUFFER_BINDING,
    SAMPLE_ALPHA_TO_COVERAGE,
    SAMPLE_COVERAGE,
    SAMPLER_BINDING,
    TEXTURE_BINDING_2D_ARRAY,
    TEXTURE_BINDING_3D,
    TRANSFORM_FEEDBACK_ACTIVE,
    TRANSFORM_FEEDBACK_BINDING,
    TRANSFORM_FEEDBACK_BUFFER_BINDING,
    TRANSFORM_FEEDBACK_PAUSED,
    UNIFORM_BUFFER_BINDING,
    UNIFORM_BUFFER_OFFSET_ALIGNMENT,
    UNPACK_IMAGE_HEIGHT,
    UNPACK_ROW_LENGTH,
    UNPACK_SKIP_IMAGES,
    UNPACK_SKIP_PIXELS,
    UNPACK_SKIP_ROWS,
    VERTEX_ARRAY_BINDING
}
declare enum PixelFormat {
    ALPHA,
    LUMINANCE,
    LUMINANCE_ALPHA,
    RGB,
    RGBA,
    RGBA4,
    RGB565,
    RGB5_A1,
    DEPTH_COMPONENT,
    DEPTH_STENCIL,
    STENCIL_INDEX8,
    R8,
    R8UI,
    R8I,
    R16UI,
    R16I,
    R32UI,
    R32I,
    RG8,
    RG8UI,
    RG8I,
    RG16UI,
    RG16I,
    RG32UI,
    RG32I,
    RGB8,
    RGBA8,
    SRGB8_ALPHA8,
    RGB10_A2,
    RGBA8UI,
    RGBA8I,
    RGB10_A2UI,
    RGBA16UI,
    RGBA16I,
    RGBA32I,
    RGBA32UI,
    DEPTH_COMPONENT24,
    DEPTH_COMPONENT32F,
    DEPTH24_STENCIL8,
    DEPTH32F_STENCIL8
}
declare enum PixelStorageMode {
    UNPACK_FLIP_Y_WEBGL,
    UNPACK_PREMULTIPLY_ALPHA_WEBGL,
    UNPACK_COLORSPACE_CONVERSION_WEBGL
}
declare enum PixelType {
    BYTE,
    FLOAT,
    FLOAT_32_UNSIGNED_INT_24_8_REV,
    HALF_FLOAT,
    INT,
    SHORT,
    UNSIGNED_BYTE,
    UNSIGNED_INT,
    UNSIGNED_INT_2_10_10_10_REV,
    UNSIGNED_INT_10F_11F_11F_REV,
    UNSIGNED_INT_5_9_9_9_REV,
    UNSIGNED_INT_24_8,
    UNSIGNED_SHORT,
    UNSIGNED_SHORT_5_6_5,
    UNSIGNED_SHORT_4_4_4_4,
    UNSIGNED_SHORT_5_5_5_1
}
declare enum RenderbufferTarget {
    RENDERBUFFER
}
declare enum Shader {
    FRAGMENT_SHADER,
    VERTEX_SHADER,
    COMPILE_STATUS,
    DELETE_STATUS,
    LINK_STATUS,
    VALIDATE_STATUS,
    ATTACHED_SHADERS,
    ACTIVE_ATTRIBUTES,
    ACTIVE_UNIFORMS,
    MAX_VERTEX_ATTRIBS,
    MAX_VERTEX_UNIFORM_VECTORS,
    MAX_VARYING_VECTORS,
    MAX_COMBINED_TEXTURE_IMAGE_UNITS,
    MAX_VERTEX_TEXTURE_IMAGE_UNITS,
    MAX_TEXTURE_IMAGE_UNITS,
    MAX_FRAGMENT_UNIFORM_VECTORS,
    SHADER_TYPE,
    SHADING_LANGUAGE_VERSION,
    CURRENT_PROGRAM
}
declare enum ShaderType {
    FRAGMENT_SHADER,
    VERTEX_SHADER
}
declare enum ShaderPrecision {
    LOW_FLOAT,
    MEDIUM_FLOAT,
    HIGH_FLOAT,
    LOW_INT,
    MEDIUM_INT,
    HIGH_INT
}
declare enum StencilAction {
    KEEP,
    REPLACE,
    INCR,
    DECR,
    INVERT,
    INCR_WRAP,
    DECR_WRAP
}
declare enum TestFunction {
    NEVER,
    LESS,
    EQUAL,
    LEQUAL,
    GREATER,
    NOTEQUAL,
    GEQUAL,
    ALWAYS
}
declare enum TextureUnits {
    TEXTURE,
    TEXTURE0
}
declare enum TextureParameter {
    TEXTURE_MAG_FILTER,
    TEXTURE_MIN_FILTER,
    TEXTURE_WRAP_S,
    TEXTURE_WRAP_T,
    TEXTURE_BASE_LEVEL,
    TEXTURE_MAX_LEVEL,
    TEXTURE_MAX_LOD,
    TEXTURE_MIN_LOD,
    TEXTURE_WRAP_R
}
declare enum TextureTarget {
    TEXTURE_2D,
    TEXTURE_CUBE_MAP,
    TEXTURE_3D,
    TEXTURE_2D_ARRAY,
    TEXTURE_CUBE_MAP_POSITIVE_X,
    TEXTURE_CUBE_MAP_NEGATIVE_X,
    TEXTURE_CUBE_MAP_POSITIVE_Y,
    TEXTURE_CUBE_MAP_NEGATIVE_Y,
    TEXTURE_CUBE_MAP_POSITIVE_Z,
    TEXTURE_CUBE_MAP_NEGATIVE_Z
}
declare enum TextureMagFilter {
    LINEAR,
    NEAREST
}
declare enum TextureMinFilter {
    LINEAR,
    NEAREST,
    NEAREST_MIPMAP_NEAREST,
    LINEAR_MIPMAP_NEAREST,
    NEAREST_MIPMAP_LINEAR,
    LINEAR_MIPMAP_LINEAR
}
declare enum TextureWrapMode {
    REPEAT,
    CLAMP_TO_EDGE,
    MIRRORED_REPEAT
}
declare enum UniformQuery {
    UNIFORM_TYPE,
    UNIFORM_SIZE,
    UNIFORM_BLOCK_INDEX,
    UNIFORM_OFFSET,
    UNIFORM_ARRAY_STRIDE,
    UNIFORM_MATRIX_STRIDE,
    UNIFORM_IS_ROW_MAJOR
}
declare enum UniformType {
    BOOL,
    BOOL_VEC2,
    BOOL_VEC3,
    BOOL_VEC4,
    INT,
    INT_VEC2,
    INT_VEC3,
    INT_VEC4,
    INT_SAMPLER_2D,
    INT_SAMPLER_3D,
    INT_SAMPLER_CUBE,
    INT_SAMPLER_2D_ARRAY,
    UNSIGNED_INT_SAMPLER_2D,
    UNSIGNED_INT_SAMPLER_3D,
    UNSIGNED_INT_SAMPLER_CUBE,
    UNSIGNED_INT_SAMPLER_2D_ARRAY,
    UNSIGNED_INT,
    UNSIGNED_INT_VEC2,
    UNSIGNED_INT_VEC3,
    UNSIGNED_INT_VEC4,
    FLOAT,
    FLOAT_VEC2,
    FLOAT_VEC3,
    FLOAT_VEC4,
    FLOAT_MAT2,
    FLOAT_MAT3,
    FLOAT_MAT4,
    FLOAT_MAT2x3,
    FLOAT_MAT2x4,
    FLOAT_MAT3x2,
    FLOAT_MAT3x4,
    FLOAT_MAT4x2,
    FLOAT_MAT4x3,
    SAMPLER_2D,
    SAMPLER_3D,
    SAMPLER_CUBE,
    SAMPLER_2D_SHADOW,
    SAMPLER_2D_ARRAY,
    SAMPLER_2D_ARRAY_SHADOW,
    SAMPLER_CUBE_SHADOW
}
declare enum VertexAttribute {
    CURRENT_VERTEX_ATTRIB,
    VERTEX_ATTRIB_ARRAY_ENABLED,
    VERTEX_ATTRIB_ARRAY_SIZE,
    VERTEX_ATTRIB_ARRAY_STRIDE,
    VERTEX_ATTRIB_ARRAY_TYPE,
    VERTEX_ATTRIB_ARRAY_NORMALIZED,
    VERTEX_ATTRIB_ARRAY_POINTER,
    VERTEX_ATTRIB_ARRAY_BUFFER_BINDING
}
